[package]
name = "aht100"
version = "0.1.0"
authors = ["Ethan Zhang <bluefurbear@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rppal = "0.11"